/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 41
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_DOT = 2,
  anon_sym_RPAREN = 3,
  anon_sym_SQUOTE = 4,
  anon_sym_BQUOTE = 5,
  anon_sym_COMMA = 6,
  sym_unquote_splicing = 7,
  sym_comment = 8,
  sym_block_comment = 9,
  anon_sym_DQUOTE = 10,
  aux_sym_string_token1 = 11,
  sym_escape_sequence = 12,
  sym_number = 13,
  sym_character = 14,
  sym_keyword = 15,
  anon_sym_t = 16,
  anon_sym_nil = 17,
  sym_symbol = 18,
  sym_program = 19,
  sym__form = 20,
  sym_list = 21,
  sym_quoting = 22,
  sym_unquoting = 23,
  sym_string = 24,
  sym_boolean = 25,
  aux_sym_program_repeat1 = 26,
  aux_sym_string_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_DOT] = ".",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_COMMA] = ",",
  [sym_unquote_splicing] = "unquote_splicing",
  [sym_comment] = "comment",
  [sym_block_comment] = "block_comment",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [sym_character] = "character",
  [sym_keyword] = "keyword",
  [anon_sym_t] = "t",
  [anon_sym_nil] = "nil",
  [sym_symbol] = "symbol",
  [sym_program] = "program",
  [sym__form] = "_form",
  [sym_list] = "list",
  [sym_quoting] = "quoting",
  [sym_unquoting] = "unquoting",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_unquote_splicing] = sym_unquote_splicing,
  [sym_comment] = sym_comment,
  [sym_block_comment] = sym_block_comment,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [sym_character] = sym_character,
  [sym_keyword] = sym_keyword,
  [anon_sym_t] = anon_sym_t,
  [anon_sym_nil] = anon_sym_nil,
  [sym_symbol] = sym_symbol,
  [sym_program] = sym_program,
  [sym__form] = sym__form,
  [sym_list] = sym_list,
  [sym_quoting] = sym_quoting,
  [sym_unquoting] = sym_unquoting,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_unquote_splicing] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_character] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nil] = {
    .visible = true,
    .named = false,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__form] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_quoting] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoting] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 2,
  [7] = 2,
  [8] = 3,
  [9] = 5,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 12,
  [14] = 11,
  [15] = 15,
  [16] = 15,
  [17] = 12,
  [18] = 18,
  [19] = 15,
  [20] = 11,
  [21] = 18,
  [22] = 18,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 25,
  [33] = 26,
  [34] = 31,
  [35] = 23,
  [36] = 24,
  [37] = 28,
  [38] = 27,
  [39] = 29,
  [40] = 30,
  [41] = 41,
  [42] = 42,
  [43] = 42,
  [44] = 41,
  [45] = 41,
  [46] = 42,
  [47] = 47,
  [48] = 48,
  [49] = 25,
  [50] = 23,
  [51] = 27,
  [52] = 28,
  [53] = 24,
  [54] = 30,
  [55] = 31,
  [56] = 29,
  [57] = 26,
  [58] = 58,
  [59] = 48,
  [60] = 58,
  [61] = 58,
  [62] = 48,
  [63] = 63,
};

static const TSCharacterRange sym_character_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'*', '+'}, {'-', ':'}, {'<', '@'}, {'[', '_'},
  {'{', 0x10ffff},
};

static const TSCharacterRange sym_symbol_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'*', '+'}, {'-', '/'}, {':', ':'}, {'<', '_'},
  {'a', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 23,
        '\'', 16,
        '(', 13,
        ')', 15,
        ',', 18,
        '.', 14,
        '/', 43,
        '0', 30,
        ';', 20,
        '?', 47,
        '\\', 53,
        '`', 17,
        'n', 48,
        't', 41,
        '+', 46,
        '-', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 23,
        '\'', 16,
        '(', 13,
        ')', 15,
        ',', 18,
        '.', 14,
        '/', 43,
        '0', 30,
        ';', 20,
        '?', 47,
        '`', 17,
        'n', 48,
        't', 41,
        '+', 46,
        '-', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == ';') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 10:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 23,
        '\'', 16,
        '(', 13,
        ',', 18,
        '.', 51,
        '/', 43,
        '0', 30,
        ';', 20,
        '?', 47,
        '`', 17,
        'n', 48,
        't', 41,
        '+', 46,
        '-', 46,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead)) ADVANCE(54);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == ')') ADVANCE(15);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ';') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(54);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COMMA);
      if (lookahead == '@') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_unquote_splicing);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_block_comment);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == ';') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(24);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_escape_sequence);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(54);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(32);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(54);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(54);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_character);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_character);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          ('\'' <= lookahead && lookahead <= ')') ||
          lookahead == ',' ||
          lookahead == ';' ||
          lookahead == '`') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_character);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(54);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_t);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_nil);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(45);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '/') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          ('\'' <= lookahead && lookahead <= ')') ||
          lookahead == ',' ||
          lookahead == ';' ||
          lookahead == '`') ADVANCE(5);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          ('\'' <= lookahead && lookahead <= ')') ||
          lookahead == ',' ||
          lookahead == ';' ||
          lookahead == '`') ADVANCE(5);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '.') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(54);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '\\') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      if ((!eof && set_contains(sym_character_character_set_1, 9, lookahead))) ADVANCE(39);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'i') ADVANCE(49);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == 'l') ADVANCE(42);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(54);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(54);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead))) ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          ('\'' <= lookahead && lookahead <= ')') ||
          lookahead == ',' ||
          lookahead == ';' ||
          lookahead == '`') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(28);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_symbol);
      if ((!eof && set_contains(sym_symbol_character_set_1, 9, lookahead)) ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 10},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 11},
  [49] = {.lex_state = 11},
  [50] = {.lex_state = 11},
  [51] = {.lex_state = 11},
  [52] = {.lex_state = 11},
  [53] = {.lex_state = 11},
  [54] = {.lex_state = 11},
  [55] = {.lex_state = 11},
  [56] = {.lex_state = 11},
  [57] = {.lex_state = 11},
  [58] = {.lex_state = 11},
  [59] = {.lex_state = 11},
  [60] = {.lex_state = 11},
  [61] = {.lex_state = 11},
  [62] = {.lex_state = 11},
  [63] = {.lex_state = 11},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_unquote_splicing] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_character] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_nil] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(63),
    [sym__form] = STATE(10),
    [sym_list] = STATE(10),
    [sym_quoting] = STATE(10),
    [sym_unquoting] = STATE(10),
    [sym_string] = STATE(10),
    [sym_boolean] = STATE(10),
    [aux_sym_program_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(11),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [sym_unquote_splicing] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [sym_character] = ACTIONS(19),
    [sym_keyword] = ACTIONS(19),
    [anon_sym_t] = ACTIONS(21),
    [anon_sym_nil] = ACTIONS(21),
    [sym_symbol] = ACTIONS(19),
  },
  [STATE(2)] = {
    [sym__form] = STATE(4),
    [sym_list] = STATE(4),
    [sym_quoting] = STATE(4),
    [sym_unquoting] = STATE(4),
    [sym_string] = STATE(4),
    [sym_boolean] = STATE(4),
    [aux_sym_program_repeat1] = STATE(4),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(31),
    [sym_unquote_splicing] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_number] = ACTIONS(37),
    [sym_character] = ACTIONS(37),
    [sym_keyword] = ACTIONS(37),
    [anon_sym_t] = ACTIONS(39),
    [anon_sym_nil] = ACTIONS(39),
    [sym_symbol] = ACTIONS(37),
  },
  [STATE(3)] = {
    [sym__form] = STATE(5),
    [sym_list] = STATE(5),
    [sym_quoting] = STATE(5),
    [sym_unquoting] = STATE(5),
    [sym_string] = STATE(5),
    [sym_boolean] = STATE(5),
    [aux_sym_program_repeat1] = STATE(5),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(31),
    [sym_unquote_splicing] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_number] = ACTIONS(45),
    [sym_character] = ACTIONS(45),
    [sym_keyword] = ACTIONS(45),
    [anon_sym_t] = ACTIONS(39),
    [anon_sym_nil] = ACTIONS(39),
    [sym_symbol] = ACTIONS(45),
  },
  [STATE(4)] = {
    [sym__form] = STATE(5),
    [sym_list] = STATE(5),
    [sym_quoting] = STATE(5),
    [sym_unquoting] = STATE(5),
    [sym_string] = STATE(5),
    [sym_boolean] = STATE(5),
    [aux_sym_program_repeat1] = STATE(5),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(47),
    [anon_sym_RPAREN] = ACTIONS(49),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(31),
    [sym_unquote_splicing] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_number] = ACTIONS(45),
    [sym_character] = ACTIONS(45),
    [sym_keyword] = ACTIONS(45),
    [anon_sym_t] = ACTIONS(39),
    [anon_sym_nil] = ACTIONS(39),
    [sym_symbol] = ACTIONS(45),
  },
  [STATE(5)] = {
    [sym__form] = STATE(5),
    [sym_list] = STATE(5),
    [sym_quoting] = STATE(5),
    [sym_unquoting] = STATE(5),
    [sym_string] = STATE(5),
    [sym_boolean] = STATE(5),
    [aux_sym_program_repeat1] = STATE(5),
    [anon_sym_LPAREN] = ACTIONS(51),
    [anon_sym_DOT] = ACTIONS(54),
    [anon_sym_RPAREN] = ACTIONS(56),
    [anon_sym_SQUOTE] = ACTIONS(58),
    [anon_sym_BQUOTE] = ACTIONS(58),
    [anon_sym_COMMA] = ACTIONS(61),
    [sym_unquote_splicing] = ACTIONS(64),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(67),
    [sym_number] = ACTIONS(70),
    [sym_character] = ACTIONS(70),
    [sym_keyword] = ACTIONS(70),
    [anon_sym_t] = ACTIONS(73),
    [anon_sym_nil] = ACTIONS(73),
    [sym_symbol] = ACTIONS(70),
  },
  [STATE(6)] = {
    [sym__form] = STATE(3),
    [sym_list] = STATE(3),
    [sym_quoting] = STATE(3),
    [sym_unquoting] = STATE(3),
    [sym_string] = STATE(3),
    [sym_boolean] = STATE(3),
    [aux_sym_program_repeat1] = STATE(3),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(76),
    [anon_sym_RPAREN] = ACTIONS(78),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(31),
    [sym_unquote_splicing] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_number] = ACTIONS(80),
    [sym_character] = ACTIONS(80),
    [sym_keyword] = ACTIONS(80),
    [anon_sym_t] = ACTIONS(39),
    [anon_sym_nil] = ACTIONS(39),
    [sym_symbol] = ACTIONS(80),
  },
  [STATE(7)] = {
    [sym__form] = STATE(8),
    [sym_list] = STATE(8),
    [sym_quoting] = STATE(8),
    [sym_unquoting] = STATE(8),
    [sym_string] = STATE(8),
    [sym_boolean] = STATE(8),
    [aux_sym_program_repeat1] = STATE(8),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(82),
    [anon_sym_RPAREN] = ACTIONS(84),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(31),
    [sym_unquote_splicing] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_number] = ACTIONS(86),
    [sym_character] = ACTIONS(86),
    [sym_keyword] = ACTIONS(86),
    [anon_sym_t] = ACTIONS(39),
    [anon_sym_nil] = ACTIONS(39),
    [sym_symbol] = ACTIONS(86),
  },
  [STATE(8)] = {
    [sym__form] = STATE(5),
    [sym_list] = STATE(5),
    [sym_quoting] = STATE(5),
    [sym_unquoting] = STATE(5),
    [sym_string] = STATE(5),
    [sym_boolean] = STATE(5),
    [aux_sym_program_repeat1] = STATE(5),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(88),
    [anon_sym_RPAREN] = ACTIONS(90),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(31),
    [sym_unquote_splicing] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_number] = ACTIONS(45),
    [sym_character] = ACTIONS(45),
    [sym_keyword] = ACTIONS(45),
    [anon_sym_t] = ACTIONS(39),
    [anon_sym_nil] = ACTIONS(39),
    [sym_symbol] = ACTIONS(45),
  },
  [STATE(9)] = {
    [sym__form] = STATE(9),
    [sym_list] = STATE(9),
    [sym_quoting] = STATE(9),
    [sym_unquoting] = STATE(9),
    [sym_string] = STATE(9),
    [sym_boolean] = STATE(9),
    [aux_sym_program_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(56),
    [anon_sym_LPAREN] = ACTIONS(92),
    [anon_sym_SQUOTE] = ACTIONS(95),
    [anon_sym_BQUOTE] = ACTIONS(95),
    [anon_sym_COMMA] = ACTIONS(98),
    [sym_unquote_splicing] = ACTIONS(101),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(104),
    [sym_number] = ACTIONS(107),
    [sym_character] = ACTIONS(107),
    [sym_keyword] = ACTIONS(107),
    [anon_sym_t] = ACTIONS(110),
    [anon_sym_nil] = ACTIONS(110),
    [sym_symbol] = ACTIONS(107),
  },
  [STATE(10)] = {
    [sym__form] = STATE(9),
    [sym_list] = STATE(9),
    [sym_quoting] = STATE(9),
    [sym_unquoting] = STATE(9),
    [sym_string] = STATE(9),
    [sym_boolean] = STATE(9),
    [aux_sym_program_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(113),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(11),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [sym_unquote_splicing] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_number] = ACTIONS(115),
    [sym_character] = ACTIONS(115),
    [sym_keyword] = ACTIONS(115),
    [anon_sym_t] = ACTIONS(21),
    [anon_sym_nil] = ACTIONS(21),
    [sym_symbol] = ACTIONS(115),
  },
  [STATE(11)] = {
    [sym__form] = STATE(33),
    [sym_list] = STATE(33),
    [sym_quoting] = STATE(33),
    [sym_unquoting] = STATE(33),
    [sym_string] = STATE(33),
    [sym_boolean] = STATE(33),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(11),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [sym_unquote_splicing] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_number] = ACTIONS(117),
    [sym_character] = ACTIONS(117),
    [sym_keyword] = ACTIONS(117),
    [anon_sym_t] = ACTIONS(21),
    [anon_sym_nil] = ACTIONS(21),
    [sym_symbol] = ACTIONS(117),
  },
  [STATE(12)] = {
    [sym__form] = STATE(62),
    [sym_list] = STATE(62),
    [sym_quoting] = STATE(62),
    [sym_unquoting] = STATE(62),
    [sym_string] = STATE(62),
    [sym_boolean] = STATE(62),
    [anon_sym_LPAREN] = ACTIONS(119),
    [anon_sym_SQUOTE] = ACTIONS(121),
    [anon_sym_BQUOTE] = ACTIONS(121),
    [anon_sym_COMMA] = ACTIONS(123),
    [sym_unquote_splicing] = ACTIONS(125),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(127),
    [sym_number] = ACTIONS(129),
    [sym_character] = ACTIONS(129),
    [sym_keyword] = ACTIONS(129),
    [anon_sym_t] = ACTIONS(131),
    [anon_sym_nil] = ACTIONS(131),
    [sym_symbol] = ACTIONS(129),
  },
  [STATE(13)] = {
    [sym__form] = STATE(48),
    [sym_list] = STATE(48),
    [sym_quoting] = STATE(48),
    [sym_unquoting] = STATE(48),
    [sym_string] = STATE(48),
    [sym_boolean] = STATE(48),
    [anon_sym_LPAREN] = ACTIONS(119),
    [anon_sym_SQUOTE] = ACTIONS(121),
    [anon_sym_BQUOTE] = ACTIONS(121),
    [anon_sym_COMMA] = ACTIONS(123),
    [sym_unquote_splicing] = ACTIONS(125),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(127),
    [sym_number] = ACTIONS(133),
    [sym_character] = ACTIONS(133),
    [sym_keyword] = ACTIONS(133),
    [anon_sym_t] = ACTIONS(131),
    [anon_sym_nil] = ACTIONS(131),
    [sym_symbol] = ACTIONS(133),
  },
  [STATE(14)] = {
    [sym__form] = STATE(26),
    [sym_list] = STATE(26),
    [sym_quoting] = STATE(26),
    [sym_unquoting] = STATE(26),
    [sym_string] = STATE(26),
    [sym_boolean] = STATE(26),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(31),
    [sym_unquote_splicing] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_number] = ACTIONS(135),
    [sym_character] = ACTIONS(135),
    [sym_keyword] = ACTIONS(135),
    [anon_sym_t] = ACTIONS(39),
    [anon_sym_nil] = ACTIONS(39),
    [sym_symbol] = ACTIONS(135),
  },
  [STATE(15)] = {
    [sym__form] = STATE(32),
    [sym_list] = STATE(32),
    [sym_quoting] = STATE(32),
    [sym_unquoting] = STATE(32),
    [sym_string] = STATE(32),
    [sym_boolean] = STATE(32),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(11),
    [anon_sym_BQUOTE] = ACTIONS(11),
    [anon_sym_COMMA] = ACTIONS(13),
    [sym_unquote_splicing] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_number] = ACTIONS(137),
    [sym_character] = ACTIONS(137),
    [sym_keyword] = ACTIONS(137),
    [anon_sym_t] = ACTIONS(21),
    [anon_sym_nil] = ACTIONS(21),
    [sym_symbol] = ACTIONS(137),
  },
  [STATE(16)] = {
    [sym__form] = STATE(25),
    [sym_list] = STATE(25),
    [sym_quoting] = STATE(25),
    [sym_unquoting] = STATE(25),
    [sym_string] = STATE(25),
    [sym_boolean] = STATE(25),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
    [anon_sym_COMMA] = ACTIONS(31),
    [sym_unquote_splicing] = ACTIONS(33),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [sym_number] = ACTIONS(139),
    [sym_character] = ACTIONS(139),
    [sym_keyword] = ACTIONS(139),
    [anon_sym_t] = ACTIONS(39),
    [anon_sym_nil] = ACTIONS(39),
    [sym_symbol] = ACTIONS(139),
  },
  [STATE(17)] = {
    [sym__form] = STATE(59),
    [sym_list] = STATE(59),
    [sym_quoting] = STATE(59),
    [sym_unquoting] = STATE(59),
    [sym_string] = STATE(59),
    [sym_boolean] = STATE(59),
    [anon_sym_LPAREN] = ACTIONS(119),
    [anon_sym_SQUOTE] = ACTIONS(121),
    [anon_sym_BQUOTE] = ACTIONS(121),
    [anon_sym_COMMA] = ACTIONS(123),
    [sym_unquote_splicing] = ACTIONS(125),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(127),
    [sym_number] = ACTIONS(141),
    [sym_character] = ACTIONS(141),
    [sym_keyword] = ACTIONS(141),
    [anon_sym_t] = ACTIONS(131),
    [anon_sym_nil] = ACTIONS(131),
    [sym_symbol] = ACTIONS(141),
  },
  [STATE(18)] = {
    [sym__form] = STATE(58),
    [sym_list] = STATE(58),
    [sym_quoting] = STATE(58),
    [sym_unquoting] = STATE(58),
    [sym_string] = STATE(58),
    [sym_boolean] = STATE(58),
    [anon_sym_LPAREN] = ACTIONS(119),
    [anon_sym_SQUOTE] = ACTIONS(121),
    [anon_sym_BQUOTE] = ACTIONS(121),
    [anon_sym_COMMA] = ACTIONS(123),
    [sym_unquote_splicing] = ACTIONS(125),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(127),
    [sym_number] = ACTIONS(143),
    [sym_character] = ACTIONS(143),
    [sym_keyword] = ACTIONS(143),
    [anon_sym_t] = ACTIONS(131),
    [anon_sym_nil] = ACTIONS(131),
    [sym_symbol] = ACTIONS(143),
  },
  [STATE(19)] = {
    [sym__form] = STATE(49),
    [sym_list] = STATE(49),
    [sym_quoting] = STATE(49),
    [sym_unquoting] = STATE(49),
    [sym_string] = STATE(49),
    [sym_boolean] = STATE(49),
    [anon_sym_LPAREN] = ACTIONS(119),
    [anon_sym_SQUOTE] = ACTIONS(121),
    [anon_sym_BQUOTE] = ACTIONS(121),
    [anon_sym_COMMA] = ACTIONS(123),
    [sym_unquote_splicing] = ACTIONS(125),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(127),
    [sym_number] = ACTIONS(145),
    [sym_character] = ACTIONS(145),
    [sym_keyword] = ACTIONS(145),
    [anon_sym_t] = ACTIONS(131),
    [anon_sym_nil] = ACTIONS(131),
    [sym_symbol] = ACTIONS(145),
  },
  [STATE(20)] = {
    [sym__form] = STATE(57),
    [sym_list] = STATE(57),
    [sym_quoting] = STATE(57),
    [sym_unquoting] = STATE(57),
    [sym_string] = STATE(57),
    [sym_boolean] = STATE(57),
    [anon_sym_LPAREN] = ACTIONS(119),
    [anon_sym_SQUOTE] = ACTIONS(121),
    [anon_sym_BQUOTE] = ACTIONS(121),
    [anon_sym_COMMA] = ACTIONS(123),
    [sym_unquote_splicing] = ACTIONS(125),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(127),
    [sym_number] = ACTIONS(147),
    [sym_character] = ACTIONS(147),
    [sym_keyword] = ACTIONS(147),
    [anon_sym_t] = ACTIONS(131),
    [anon_sym_nil] = ACTIONS(131),
    [sym_symbol] = ACTIONS(147),
  },
  [STATE(21)] = {
    [sym__form] = STATE(60),
    [sym_list] = STATE(60),
    [sym_quoting] = STATE(60),
    [sym_unquoting] = STATE(60),
    [sym_string] = STATE(60),
    [sym_boolean] = STATE(60),
    [anon_sym_LPAREN] = ACTIONS(119),
    [anon_sym_SQUOTE] = ACTIONS(121),
    [anon_sym_BQUOTE] = ACTIONS(121),
    [anon_sym_COMMA] = ACTIONS(123),
    [sym_unquote_splicing] = ACTIONS(125),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(127),
    [sym_number] = ACTIONS(149),
    [sym_character] = ACTIONS(149),
    [sym_keyword] = ACTIONS(149),
    [anon_sym_t] = ACTIONS(131),
    [anon_sym_nil] = ACTIONS(131),
    [sym_symbol] = ACTIONS(149),
  },
  [STATE(22)] = {
    [sym__form] = STATE(61),
    [sym_list] = STATE(61),
    [sym_quoting] = STATE(61),
    [sym_unquoting] = STATE(61),
    [sym_string] = STATE(61),
    [sym_boolean] = STATE(61),
    [anon_sym_LPAREN] = ACTIONS(119),
    [anon_sym_SQUOTE] = ACTIONS(121),
    [anon_sym_BQUOTE] = ACTIONS(121),
    [anon_sym_COMMA] = ACTIONS(123),
    [sym_unquote_splicing] = ACTIONS(125),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(127),
    [sym_number] = ACTIONS(151),
    [sym_character] = ACTIONS(151),
    [sym_keyword] = ACTIONS(151),
    [anon_sym_t] = ACTIONS(131),
    [anon_sym_nil] = ACTIONS(131),
    [sym_symbol] = ACTIONS(151),
  },
  [STATE(23)] = {
    [anon_sym_LPAREN] = ACTIONS(153),
    [anon_sym_DOT] = ACTIONS(155),
    [anon_sym_RPAREN] = ACTIONS(153),
    [anon_sym_SQUOTE] = ACTIONS(153),
    [anon_sym_BQUOTE] = ACTIONS(153),
    [anon_sym_COMMA] = ACTIONS(155),
    [sym_unquote_splicing] = ACTIONS(153),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(153),
    [sym_number] = ACTIONS(155),
    [sym_character] = ACTIONS(155),
    [sym_keyword] = ACTIONS(155),
    [anon_sym_t] = ACTIONS(155),
    [anon_sym_nil] = ACTIONS(155),
    [sym_symbol] = ACTIONS(155),
  },
  [STATE(24)] = {
    [anon_sym_LPAREN] = ACTIONS(157),
    [anon_sym_DOT] = ACTIONS(159),
    [anon_sym_RPAREN] = ACTIONS(157),
    [anon_sym_SQUOTE] = ACTIONS(157),
    [anon_sym_BQUOTE] = ACTIONS(157),
    [anon_sym_COMMA] = ACTIONS(159),
    [sym_unquote_splicing] = ACTIONS(157),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(157),
    [sym_number] = ACTIONS(159),
    [sym_character] = ACTIONS(159),
    [sym_keyword] = ACTIONS(159),
    [anon_sym_t] = ACTIONS(159),
    [anon_sym_nil] = ACTIONS(159),
    [sym_symbol] = ACTIONS(159),
  },
  [STATE(25)] = {
    [anon_sym_LPAREN] = ACTIONS(161),
    [anon_sym_DOT] = ACTIONS(163),
    [anon_sym_RPAREN] = ACTIONS(161),
    [anon_sym_SQUOTE] = ACTIONS(161),
    [anon_sym_BQUOTE] = ACTIONS(161),
    [anon_sym_COMMA] = ACTIONS(163),
    [sym_unquote_splicing] = ACTIONS(161),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(161),
    [sym_number] = ACTIONS(163),
    [sym_character] = ACTIONS(163),
    [sym_keyword] = ACTIONS(163),
    [anon_sym_t] = ACTIONS(163),
    [anon_sym_nil] = ACTIONS(163),
    [sym_symbol] = ACTIONS(163),
  },
  [STATE(26)] = {
    [anon_sym_LPAREN] = ACTIONS(165),
    [anon_sym_DOT] = ACTIONS(167),
    [anon_sym_RPAREN] = ACTIONS(165),
    [anon_sym_SQUOTE] = ACTIONS(165),
    [anon_sym_BQUOTE] = ACTIONS(165),
    [anon_sym_COMMA] = ACTIONS(167),
    [sym_unquote_splicing] = ACTIONS(165),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(165),
    [sym_number] = ACTIONS(167),
    [sym_character] = ACTIONS(167),
    [sym_keyword] = ACTIONS(167),
    [anon_sym_t] = ACTIONS(167),
    [anon_sym_nil] = ACTIONS(167),
    [sym_symbol] = ACTIONS(167),
  },
  [STATE(27)] = {
    [anon_sym_LPAREN] = ACTIONS(169),
    [anon_sym_DOT] = ACTIONS(171),
    [anon_sym_RPAREN] = ACTIONS(169),
    [anon_sym_SQUOTE] = ACTIONS(169),
    [anon_sym_BQUOTE] = ACTIONS(169),
    [anon_sym_COMMA] = ACTIONS(171),
    [sym_unquote_splicing] = ACTIONS(169),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(169),
    [sym_number] = ACTIONS(171),
    [sym_character] = ACTIONS(171),
    [sym_keyword] = ACTIONS(171),
    [anon_sym_t] = ACTIONS(171),
    [anon_sym_nil] = ACTIONS(171),
    [sym_symbol] = ACTIONS(171),
  },
  [STATE(28)] = {
    [anon_sym_LPAREN] = ACTIONS(173),
    [anon_sym_DOT] = ACTIONS(175),
    [anon_sym_RPAREN] = ACTIONS(173),
    [anon_sym_SQUOTE] = ACTIONS(173),
    [anon_sym_BQUOTE] = ACTIONS(173),
    [anon_sym_COMMA] = ACTIONS(175),
    [sym_unquote_splicing] = ACTIONS(173),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(173),
    [sym_number] = ACTIONS(175),
    [sym_character] = ACTIONS(175),
    [sym_keyword] = ACTIONS(175),
    [anon_sym_t] = ACTIONS(175),
    [anon_sym_nil] = ACTIONS(175),
    [sym_symbol] = ACTIONS(175),
  },
  [STATE(29)] = {
    [anon_sym_LPAREN] = ACTIONS(177),
    [anon_sym_DOT] = ACTIONS(179),
    [anon_sym_RPAREN] = ACTIONS(177),
    [anon_sym_SQUOTE] = ACTIONS(177),
    [anon_sym_BQUOTE] = ACTIONS(177),
    [anon_sym_COMMA] = ACTIONS(179),
    [sym_unquote_splicing] = ACTIONS(177),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(177),
    [sym_number] = ACTIONS(179),
    [sym_character] = ACTIONS(179),
    [sym_keyword] = ACTIONS(179),
    [anon_sym_t] = ACTIONS(179),
    [anon_sym_nil] = ACTIONS(179),
    [sym_symbol] = ACTIONS(179),
  },
  [STATE(30)] = {
    [anon_sym_LPAREN] = ACTIONS(181),
    [anon_sym_DOT] = ACTIONS(183),
    [anon_sym_RPAREN] = ACTIONS(181),
    [anon_sym_SQUOTE] = ACTIONS(181),
    [anon_sym_BQUOTE] = ACTIONS(181),
    [anon_sym_COMMA] = ACTIONS(183),
    [sym_unquote_splicing] = ACTIONS(181),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(181),
    [sym_number] = ACTIONS(183),
    [sym_character] = ACTIONS(183),
    [sym_keyword] = ACTIONS(183),
    [anon_sym_t] = ACTIONS(183),
    [anon_sym_nil] = ACTIONS(183),
    [sym_symbol] = ACTIONS(183),
  },
  [STATE(31)] = {
    [anon_sym_LPAREN] = ACTIONS(185),
    [anon_sym_DOT] = ACTIONS(187),
    [anon_sym_RPAREN] = ACTIONS(185),
    [anon_sym_SQUOTE] = ACTIONS(185),
    [anon_sym_BQUOTE] = ACTIONS(185),
    [anon_sym_COMMA] = ACTIONS(187),
    [sym_unquote_splicing] = ACTIONS(185),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(185),
    [sym_number] = ACTIONS(187),
    [sym_character] = ACTIONS(187),
    [sym_keyword] = ACTIONS(187),
    [anon_sym_t] = ACTIONS(187),
    [anon_sym_nil] = ACTIONS(187),
    [sym_symbol] = ACTIONS(187),
  },
  [STATE(32)] = {
    [ts_builtin_sym_end] = ACTIONS(161),
    [anon_sym_LPAREN] = ACTIONS(161),
    [anon_sym_SQUOTE] = ACTIONS(161),
    [anon_sym_BQUOTE] = ACTIONS(161),
    [anon_sym_COMMA] = ACTIONS(163),
    [sym_unquote_splicing] = ACTIONS(161),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(161),
    [sym_number] = ACTIONS(163),
    [sym_character] = ACTIONS(163),
    [sym_keyword] = ACTIONS(163),
    [anon_sym_t] = ACTIONS(163),
    [anon_sym_nil] = ACTIONS(163),
    [sym_symbol] = ACTIONS(163),
  },
  [STATE(33)] = {
    [ts_builtin_sym_end] = ACTIONS(165),
    [anon_sym_LPAREN] = ACTIONS(165),
    [anon_sym_SQUOTE] = ACTIONS(165),
    [anon_sym_BQUOTE] = ACTIONS(165),
    [anon_sym_COMMA] = ACTIONS(167),
    [sym_unquote_splicing] = ACTIONS(165),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(165),
    [sym_number] = ACTIONS(167),
    [sym_character] = ACTIONS(167),
    [sym_keyword] = ACTIONS(167),
    [anon_sym_t] = ACTIONS(167),
    [anon_sym_nil] = ACTIONS(167),
    [sym_symbol] = ACTIONS(167),
  },
  [STATE(34)] = {
    [ts_builtin_sym_end] = ACTIONS(185),
    [anon_sym_LPAREN] = ACTIONS(185),
    [anon_sym_SQUOTE] = ACTIONS(185),
    [anon_sym_BQUOTE] = ACTIONS(185),
    [anon_sym_COMMA] = ACTIONS(187),
    [sym_unquote_splicing] = ACTIONS(185),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(185),
    [sym_number] = ACTIONS(187),
    [sym_character] = ACTIONS(187),
    [sym_keyword] = ACTIONS(187),
    [anon_sym_t] = ACTIONS(187),
    [anon_sym_nil] = ACTIONS(187),
    [sym_symbol] = ACTIONS(187),
  },
  [STATE(35)] = {
    [ts_builtin_sym_end] = ACTIONS(153),
    [anon_sym_LPAREN] = ACTIONS(153),
    [anon_sym_SQUOTE] = ACTIONS(153),
    [anon_sym_BQUOTE] = ACTIONS(153),
    [anon_sym_COMMA] = ACTIONS(155),
    [sym_unquote_splicing] = ACTIONS(153),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(153),
    [sym_number] = ACTIONS(155),
    [sym_character] = ACTIONS(155),
    [sym_keyword] = ACTIONS(155),
    [anon_sym_t] = ACTIONS(155),
    [anon_sym_nil] = ACTIONS(155),
    [sym_symbol] = ACTIONS(155),
  },
  [STATE(36)] = {
    [ts_builtin_sym_end] = ACTIONS(157),
    [anon_sym_LPAREN] = ACTIONS(157),
    [anon_sym_SQUOTE] = ACTIONS(157),
    [anon_sym_BQUOTE] = ACTIONS(157),
    [anon_sym_COMMA] = ACTIONS(159),
    [sym_unquote_splicing] = ACTIONS(157),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(157),
    [sym_number] = ACTIONS(159),
    [sym_character] = ACTIONS(159),
    [sym_keyword] = ACTIONS(159),
    [anon_sym_t] = ACTIONS(159),
    [anon_sym_nil] = ACTIONS(159),
    [sym_symbol] = ACTIONS(159),
  },
  [STATE(37)] = {
    [ts_builtin_sym_end] = ACTIONS(173),
    [anon_sym_LPAREN] = ACTIONS(173),
    [anon_sym_SQUOTE] = ACTIONS(173),
    [anon_sym_BQUOTE] = ACTIONS(173),
    [anon_sym_COMMA] = ACTIONS(175),
    [sym_unquote_splicing] = ACTIONS(173),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(173),
    [sym_number] = ACTIONS(175),
    [sym_character] = ACTIONS(175),
    [sym_keyword] = ACTIONS(175),
    [anon_sym_t] = ACTIONS(175),
    [anon_sym_nil] = ACTIONS(175),
    [sym_symbol] = ACTIONS(175),
  },
  [STATE(38)] = {
    [ts_builtin_sym_end] = ACTIONS(169),
    [anon_sym_LPAREN] = ACTIONS(169),
    [anon_sym_SQUOTE] = ACTIONS(169),
    [anon_sym_BQUOTE] = ACTIONS(169),
    [anon_sym_COMMA] = ACTIONS(171),
    [sym_unquote_splicing] = ACTIONS(169),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(169),
    [sym_number] = ACTIONS(171),
    [sym_character] = ACTIONS(171),
    [sym_keyword] = ACTIONS(171),
    [anon_sym_t] = ACTIONS(171),
    [anon_sym_nil] = ACTIONS(171),
    [sym_symbol] = ACTIONS(171),
  },
  [STATE(39)] = {
    [ts_builtin_sym_end] = ACTIONS(177),
    [anon_sym_LPAREN] = ACTIONS(177),
    [anon_sym_SQUOTE] = ACTIONS(177),
    [anon_sym_BQUOTE] = ACTIONS(177),
    [anon_sym_COMMA] = ACTIONS(179),
    [sym_unquote_splicing] = ACTIONS(177),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(177),
    [sym_number] = ACTIONS(179),
    [sym_character] = ACTIONS(179),
    [sym_keyword] = ACTIONS(179),
    [anon_sym_t] = ACTIONS(179),
    [anon_sym_nil] = ACTIONS(179),
    [sym_symbol] = ACTIONS(179),
  },
  [STATE(40)] = {
    [ts_builtin_sym_end] = ACTIONS(181),
    [anon_sym_LPAREN] = ACTIONS(181),
    [anon_sym_SQUOTE] = ACTIONS(181),
    [anon_sym_BQUOTE] = ACTIONS(181),
    [anon_sym_COMMA] = ACTIONS(183),
    [sym_unquote_splicing] = ACTIONS(181),
    [sym_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(181),
    [sym_number] = ACTIONS(183),
    [sym_character] = ACTIONS(183),
    [sym_keyword] = ACTIONS(183),
    [anon_sym_t] = ACTIONS(183),
    [anon_sym_nil] = ACTIONS(183),
    [sym_symbol] = ACTIONS(183),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(189), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_string_repeat1,
    ACTIONS(5), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(191), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [15] = 4,
    ACTIONS(193), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      aux_sym_string_repeat1,
    ACTIONS(5), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(195), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [30] = 4,
    ACTIONS(197), 1,
      anon_sym_DQUOTE,
    STATE(45), 1,
      aux_sym_string_repeat1,
    ACTIONS(5), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(199), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [45] = 4,
    ACTIONS(201), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_string_repeat1,
    ACTIONS(5), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(191), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [60] = 4,
    ACTIONS(203), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_string_repeat1,
    ACTIONS(5), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(191), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [75] = 4,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      aux_sym_string_repeat1,
    ACTIONS(5), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(207), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [90] = 4,
    ACTIONS(209), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_string_repeat1,
    ACTIONS(5), 2,
      sym_comment,
      sym_block_comment,
    ACTIONS(211), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [105] = 2,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [113] = 2,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [121] = 2,
    ACTIONS(153), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [129] = 2,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [137] = 2,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [145] = 2,
    ACTIONS(157), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [153] = 2,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [161] = 2,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [169] = 2,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [177] = 2,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [185] = 2,
    ACTIONS(216), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [193] = 2,
    ACTIONS(218), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [201] = 2,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [209] = 2,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [217] = 2,
    ACTIONS(224), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
  [225] = 2,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(41)] = 0,
  [SMALL_STATE(42)] = 15,
  [SMALL_STATE(43)] = 30,
  [SMALL_STATE(44)] = 45,
  [SMALL_STATE(45)] = 60,
  [SMALL_STATE(46)] = 75,
  [SMALL_STATE(47)] = 90,
  [SMALL_STATE(48)] = 105,
  [SMALL_STATE(49)] = 113,
  [SMALL_STATE(50)] = 121,
  [SMALL_STATE(51)] = 129,
  [SMALL_STATE(52)] = 137,
  [SMALL_STATE(53)] = 145,
  [SMALL_STATE(54)] = 153,
  [SMALL_STATE(55)] = 161,
  [SMALL_STATE(56)] = 169,
  [SMALL_STATE(57)] = 177,
  [SMALL_STATE(58)] = 185,
  [SMALL_STATE(59)] = 193,
  [SMALL_STATE(60)] = 201,
  [SMALL_STATE(61)] = 209,
  [SMALL_STATE(62)] = 217,
  [SMALL_STATE(63)] = 225,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoting, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoting, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquoting, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquoting, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [211] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [226] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_skill(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
