id = "skill"
name = "Skill"
version = "0.2.0"
schema_version = 1
description = "Language support for Cadence SKILL - syntax highlighting, code completion, go to definition, hover, diagnostics, and more"
repository = "https://github.com/deanyou/zed-skill"
authors = ["Dean You"]
themes = []
icon_themes = []
languages = ["languages/skill"]
capabilities = []

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.skill]
repository = "https://github.com/deanyou/zed-skill"
rev = "082f7fc177e39b912a67aa1ab38ed64b7ee84a33"
path = "tree-sitter-skill"

[language_servers.skill-lsp]
languages = ["Skill"]

[language_servers.skill-lsp.language_ids]

[context_servers]

[slash_commands]
